# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import PyQt5.QtWidgets as qtw
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(361, 588)
        font = QtGui.QFont()
        font.setPointSize(26)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.OutputLabel = QtWidgets.QLabel(self.centralwidget)
        self.OutputLabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.OutputLabel.setFont(font)
        self.OutputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.OutputLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OutputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.OutputLabel.setObjectName("OutputLabel")
        self.percent = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("%"))
        self.percent.setGeometry(QtCore.QRect(10, 110, 75, 75))
        self.percent.setObjectName("percent")
        self.cbutton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("C"))
        self.cbutton.setGeometry(QtCore.QRect(100, 110, 75, 75))
        self.cbutton.setObjectName("cbutton")
        self.arrow = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.remove_it())
        self.arrow.setGeometry(QtCore.QRect(190, 110, 75, 75))
        self.arrow.setObjectName("arrow")
        self.divide = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("/"))
        self.divide.setGeometry(QtCore.QRect(275, 110, 75, 75))
        self.divide.setObjectName("divide")
        self.eight = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("8"))
        self.eight.setGeometry(QtCore.QRect(100, 200, 75, 75))
        self.eight.setObjectName("eight")
        self.times = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("*"))
        self.times.setGeometry(QtCore.QRect(275, 200, 75, 75))
        self.times.setObjectName("times")
        self.nine = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("9"))
        self.nine.setGeometry(QtCore.QRect(190, 200, 75, 75))
        self.nine.setObjectName("nine")
        self.seven = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("7"))
        self.seven.setGeometry(QtCore.QRect(10, 200, 75, 75))
        self.seven.setObjectName("seven")
        self.two = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("2"))
        self.two.setGeometry(QtCore.QRect(100, 370, 75, 75))
        self.two.setObjectName("two")
        self.plus = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("+"))
        self.plus.setGeometry(QtCore.QRect(275, 370, 75, 75))
        self.plus.setObjectName("plus")
        self.three = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("3"))
        self.three.setGeometry(QtCore.QRect(190, 370, 75, 75))
        self.three.setObjectName("three")
        self.one = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("1"))
        self.one.setGeometry(QtCore.QRect(10, 370, 75, 75))
        self.one.setObjectName("one")
        self.five = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("5"))
        self.five.setGeometry(QtCore.QRect(100, 290, 75, 75))
        self.five.setObjectName("five")
        self.minus = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("-"))
        self.minus.setGeometry(QtCore.QRect(275, 290, 75, 75))
        self.minus.setObjectName("minus")
        self.six = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("6"))
        self.six.setGeometry(QtCore.QRect(190, 290, 75, 75))
        self.six.setObjectName("six")
        self.four = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("4"))
        self.four.setGeometry(QtCore.QRect(10, 290, 75, 75))
        self.four.setObjectName("four")
        self.zero = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.press_it("0"))
        self.zero.setGeometry(QtCore.QRect(100, 450, 75, 75))
        self.zero.setObjectName("zero")
        self.equal = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.math_it())
        self.equal.setGeometry(QtCore.QRect(275, 450, 75, 75))
        self.equal.setObjectName("equal")
        self.dot = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.dot_it())
        self.dot.setGeometry(QtCore.QRect(190, 450, 75, 75))
        self.dot.setObjectName("dot")
        self.plusminus = QtWidgets.QPushButton(self.centralwidget , clicked = lambda: self.plus_minus_it())
        self.plusminus.setGeometry(QtCore.QRect(10, 450, 75, 75))
        self.plusminus.setObjectName("plusminus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def math_it(self):
        screen = self.OutputLabel.text()
        try:
            answer = eval(screen)
            self.OutputLabel.setText(str(answer)) 
        except:
            self.OutputLabel.setText("ERROR")  

    def remove_it(self):
        screen = self.OutputLabel.text()
        screen = screen[:-1]
        self.OutputLabel.setText(screen)

    def plus_minus_it(self):
        screen = self.OutputLabel.text()
        if "-" in screen:
            self.OutputLabel.setText(screen.replace("-",""))
        else:
            self.OutputLabel.setText(f'-{screen}')    

    def dot_it(self):
            screen = self.OutputLabel.text()
            if screen[-1] == ".":
                pass
            else:
                self.OutputLabel.setText(f'{screen}.')

    def press_it(self,pressed):
        if pressed =="C":
            self.OutputLabel.setText("0")
        else:
            if self.OutputLabel.text() == "0":
                self.OutputLabel.setText("")    
            self.OutputLabel.setText(f' {self.OutputLabel.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.OutputLabel.setText(_translate("MainWindow", "0"))
        self.percent.setText(_translate("MainWindow", "%"))
        self.cbutton.setText(_translate("MainWindow", "C"))
        self.arrow.setText(_translate("MainWindow", "<<"))
        self.divide.setText(_translate("MainWindow", "/"))
        self.eight.setText(_translate("MainWindow", "8"))
        self.times.setText(_translate("MainWindow", "x"))
        self.nine.setText(_translate("MainWindow", "9"))
        self.seven.setText(_translate("MainWindow", "7"))
        self.two.setText(_translate("MainWindow", "2"))
        self.plus.setText(_translate("MainWindow", "+"))
        self.three.setText(_translate("MainWindow", "3"))
        self.one.setText(_translate("MainWindow", "1"))
        self.five.setText(_translate("MainWindow", "5"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.six.setText(_translate("MainWindow", "6"))
        self.four.setText(_translate("MainWindow", "4"))
        self.zero.setText(_translate("MainWindow", "0"))
        self.equal.setText(_translate("MainWindow", "="))
        self.dot.setText(_translate("MainWindow", "."))
        self.plusminus.setText(_translate("MainWindow", "+/-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
